// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.junit.BeforeClass;
import org.junit.AfterClass;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.*;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;
public class Selenium_T01 {
  private ChromeDriver driver;
  //private Map<String, Object> vars;
  //JavascriptExecutor js;
  @Before
  public void setUp() {
    //driver = new ChromeDriver();
    //js = (JavascriptExecutor) driver;
	//vars = new HashMap<String, Object>();
    
	ChromeOptions options = new ChromeOptions();
	options.addArguments("--remote-allow-origins=*");
	driver = new ChromeDriver(options);

  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testrec1() {
    // Test name: test_rec1
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://web-kalimanjaro.aws.swinfra.net/");
    // 2 | setWindowSize | 1050x863 | 
    driver.manage().window().setSize(new Dimension(1050, 863));
    // 3 | click | linkText=All kind of CGI's. | 
    driver.findElement(By.linkText("All kind of CGI\'s.")).click();
    // 4 | click | linkText=Example 1 | 
    driver.findElement(By.linkText("Example 1")).click();
    // 5 | click | name=entry | 
    driver.findElement(By.name("entry")).click();
    // 6 | type | name=entry | test
    driver.findElement(By.name("entry")).sendKeys("test");
    // 7 | click | css=p > input | 
    driver.findElement(By.cssSelector("p > input")).click();
    // 8 | click | css=body | 
    driver.findElement(By.cssSelector("body")).click();
    // 9 | click | css=body | 
    driver.findElement(By.cssSelector("body")).click();
  }
}
